### ISSUE TITLE
Getting 404 error for a file.

### ISSUE THREAD

**Issue by Ishank-dubey** [PredixDev/px-context-browser#23] opened 2016-12-02 16:22 UTC
I am getting the attached error on the console when I use the component.
Can anyone help removing those?
![cb1](https://cloud.githubusercontent.com/assets/1701231/20841363/885df6e4-b8d9-11e6-9c81-e886a64d59dd.PNG)

The bower file is - 
"dependencies": {
    "angular": "1.5.8",
    "angular-route": "1.5.x",
    "bootstrap": "3.3.x",
    "angular-mocks": "1.5.x",
    "angular-bootstrap": "latest",
    "px-spinner": "latest",
    "px-context-browser": null,
    "q": "#1.0.1",
    "px-dropdown": "^0.12.2",
    "px-data-table": "https://github.com/PredixDev/px-data-table.git#^1.14.4",
    "px-alert-message": "^0.7.20"
  },
  "resolutions": {
    "angular": "1.5.8",
    "polymer": "^v1.6.0",
    "polymer-font-awesome": "0.1.9",
    "px-theme": "~v1.1.2",
    "px-defaults-design": "^0.3.0",
    "px-functions-design": "~1.0.0",
    "px-typography-design": "^1.1.3",
    "px-iconography-design": "^0.2.10",
    "px-alert-message": "^0.7.20",
    "px-actionable-text-icons": "^0.1.0"
  }

**Comment by randyaskin** [comment] 2016-12-02 18:21
Resolutions are generally a bad sign in a bower file because it means your dependencies are out of sync. Also, `latest` is generally frowned upon because you could pull in major API-breaking changes, and I don't think `null` is even a valid SemVer option.

I would recommend removing the resolutions block, updating the dependencies to the following (I'm only showing the px-* ones), removing your `bower_components` folder, and re-running `bower install`. It should run cleanly and shouldn't ask for any resolutions.

```
"dependencies": {
"px-spinner": "^0.4.0",
"px-context-browser": "^1.3.0",
"px-dropdown": "^2.0.0",
"px-data-table": "^1.14.0",
"px-alert-message": "^0.7.0"
}
```

**Comment by runn-vermel** [comment] 2016-12-30 18:49
closing issue - please re-open if the issue isn't resolved once you've run the instructions @randyaskin left above.

**Closed by runn-vermel** 2016-12-30 18:49 UTC
